# Конфигурация службы Media Scanner
# Путь для сканирования использовать абсолютный путь для службы
path = /var/media_storage

# Интервал сканирования в секундах
interval = 60

# Включить HTTP-сервер
http_mode = 1

# Порт HTTP-сервера
port = 8080